added some colouring options from ubuntu shell, completions & theme defaults

diff --git a/_bashrc b/_bashrc
--- a/_bashrc
+++ b/_bashrc
@@ -17,6 +17,10 @@ export EDITOR
 # shopt -s no_empty_cmd_completion
 # shopt -s cmdhist # save all lines of a multiple-line command in the same history entry
 
+# Load composure first, so we support function metadata
+. "${HOME}/sys_bashrc/modules/composure.sh"
+# support 'plumbing' metadata
+cite _about _param _example _group _author _version
 
 # Source bashrc assets
 . "${HOME}/sys_bashrc/theme_settings.sh"
@@ -32,6 +36,15 @@ export EDITOR
 . "${HOME}/sys_bashrc/aliases/git_aliases.sh"
 
 # source completions
+if ! shopt -oq posix; then
+  if [ -f /usr/share/bash-completion/bash_completion ]; then
+    . /usr/share/bash-completion/bash_completion
+  elif [ -f /etc/bash_completion ]; then
+    . /etc/bash_completion
+  fi
+fi
+
+
 . "${HOME}/sys_bashrc/completions/docker_completion.sh"
 . "${HOME}/sys_bashrc/completions/docker-compose_completion.sh"
 . "${HOME}/sys_bashrc/completions/awscli_completion.sh"
@@ -46,6 +59,10 @@ export EDITOR
 . "${HOME}/sys_bashrc/modules/git_module.sh"
 . "${HOME}/sys_bashrc/modules/history_module.sh"
 
+#################################################################
+# make less more friendly for non-text input files, see lesspipe
+[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
+
 # Color for manpages in less makes manpages a little easier to read
 export LESS_TERMCAP_mb=$'\E[38;5;221m'
 export LESS_TERMCAP_md=$'\E[38;5;221m'
@@ -55,74 +72,82 @@ export LESS_TERMCAP_so=$'\E[01;44;33m'
 export LESS_TERMCAP_ue=$'\E[0m'
 export LESS_TERMCAP_us=$'\E[01;35m'
 
+#################################################################
+# enable dircolor  support
+if [ -x /usr/bin/dircolors ]; then
+    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
+fi
+
 
 #################################################################
 #################################################################
 #################################################################
-# User specific aliases and functions
+# PS prompt stuff
 
 # https://superuser.com/questions/288714/bash-autocomplete-like-zsh
 bind 'set show-all-if-ambiguous on'
 bind 'set colored-completion-prefix on'
 
 
-function prompt_command() {
-    ###################################################
-    ### identify success/fail status of last command
-    ### DO NOT MOVE THIS VARIABLE: must be first!
-    local last_status="$?"
-    ###################################################
-    ###################################################
-    #timer_stop
-    ###################################################
-    ###################################################
-    ### Setup if else for different color themes
-    PATH_COL_VAR="${SET_PATHCOL_VAR}"
-    PATH_COL="${SET_PATHCOL}"
-    THEME_VAR="${SET_THEME_VAR}"
-    BARCOL="${SET_BARCOL}"
-    TXTCOL="${SET_TXTCOL}"
+FULL_PROMPT="$SET_FULL_PROMPT" # set in theme_settings.sh
+if [ "$FULL_PROMPT" == "yes" ]; then
+    function prompt_command() {
+        ###################################################
+        ### identify success/fail status of last command
+        ### DO NOT MOVE THIS VARIABLE: must be first!
+        local last_status="$?"
+        ###################################################
+        ###################################################
+        #timer_stop
+        ###################################################
+        ###################################################
+        ### Setup if else for different color themes
+        PATH_COL_VAR="${SET_PATHCOL_VAR}"
+        PATH_COL="${SET_PATHCOL}"
+        THEME_VAR="${SET_THEME_VAR}"
+        BARCOL="${SET_BARCOL}"
+        TXTCOL="${SET_TXTCOL}"
 
-    ###################################################
-    ### Turn the prompt symbol red if the user is root
-    ### root stuff
-    if [[ $(id -u) -eq 0 ]]; then
-        ### root color
-        BARCOL="${MORANGE}"
-        TXTCOL="${RED}"
-        local ENDBIT="#"
-    else
-        local ENDBIT="$"
-    fi # root bit
+        ###################################################
+        ### Turn the prompt symbol red if the user is root
+        ### root stuff
+        if [[ $(id -u) -eq 0 ]]; then
+            ### root color
+            BARCOL="${MORANGE}"
+            TXTCOL="${RED}"
+            local ENDBIT="#"
+        else
+            local ENDBIT="$"
+        fi # root bit
 
-    ###################################################
-    ### Display virtual environment notification  if applicable
-    ## disable the default virtualenv prompt change
-    export VIRTUAL_ENV_DISABLE_PROMPT=1
+        ###################################################
+        ### Display virtual environment notification  if applicable
+        ## disable the default virtualenv prompt change
+        export VIRTUAL_ENV_DISABLE_PROMPT=1
 
-    VIRTENV=$(virtualenv_info)
+        VIRTENV=$(virtualenv_info)
 
-    ### Display ssh variable notification in prompt if applicable
-    SSH_SESSION=$(ssh_info)
+        ### Display ssh variable notification in prompt if applicable
+        SSH_SESSION=$(ssh_info)
 
-    ### Display AWS profile if applicable
-    CURR_AWS_PROFILE=$(aws_info)
+        ### Display AWS profile if applicable
+        CURR_AWS_PROFILE=$(aws_info)
 
-    # Display tty no in prompt
-    local TTY_VAR=`tty 2> /dev/null | awk -F/ '{nlast = NF 0;print $nlast$NF": "}'`
+        # Display tty no in prompt
+        local TTY_VAR=`tty 2> /dev/null | awk -F/ '{nlast = NF 0;print $nlast$NF": "}'`
 
-    ###################################################
-    ### set color coded error string for prompt depending on success of last command
-    if [[ $last_status == 0 ]]; then
-        ERRPROMPT="\[\033[1;1;32m\]${ENDBIT} "
-    else
-        ERRPROMPT='\[\033[1;1;31m\]X '
-    fi
+        ###################################################
+        ### set color coded error string for prompt depending on success of last command
+        if [[ $last_status == 0 ]]; then
+            ERRPROMPT="\[\033[1;1;32m\]${ENDBIT} "
+        else
+            ERRPROMPT='\[\033[1;1;31m\]X '
+        fi
 
-    ###################################################
-    ### set titlebar
-    local TITLEBAR=`pwdtail`
-    echo -ne '\033]2;'${TTY_VAR}${TITLEBAR}'\007'
+        ###################################################
+        ### set titlebar
+        local TITLEBAR=`pwdtail`
+        echo -ne '\033]2;'${TTY_VAR}${TITLEBAR}'\007'
 
 ## move out of indented tabs to avoid formatting horror (still in function)
 PS1="${debian_chroot:+($debian_chroot)}\n\
@@ -139,9 +164,48 @@ ${BARCOL}─\
 ${ERRPROMPT}${TERGREEN}"
 }
 
+else
+    function prompt_command() {
+        PATH_COL_VAR="${SET_PATHCOL_VAR}"
+        PATH_COL="${SET_PATHCOL}"
+        THEME_VAR="${SET_THEME_VAR}"
+        BARCOL="${SET_BARCOL}"
+        TXTCOL="${SET_TXTCOL}"
 
+        ###################################################
+        ### Display virtual environment notification  if applicable
+        ## disable the default virtualenv prompt change
+        export VIRTUAL_ENV_DISABLE_PROMPT=1
 
+        VIRTENV=$(virtualenv_min_info)
+
+        ### Display ssh variable notification in prompt if applicable
+        SSH_SESSION=$(ssh_info)
+
+        ### get parent directory
+        FULL_PATH=$(pwd)
+        LAST2_DIR=${FULL_PATH#"${FULL_PATH%/*/*}/"}
+
+        #DRIVE_PATH=$(df . | tail -1 | awk '{print $1}')
+        #DRIVE_ID=${DRIVE_PATH#"${DRIVE_PATH%/*}/"}
+
+## move out of indented tabs to avoid formatting horror (still in function)
+PS1="${debian_chroot:+($debian_chroot)}\n\
+${BARCOL}\
+${TXTCOL}(`date +"%H:%M"`)${BARCOL}─${TXTCOL}(\u@\H)\
+${BARCOL}─${GRAY}(${GRAY}${LAST2_DIR})\
+$(parse_git_minimal)\n\
+${BARCOL}\
+${RED}${VIRTENV} \[\033[1;1;32m\]$ ${TERGREEN}"
+}
+
+fi
+
+#################################################################
+#################################################################
+#################################################################
 # history guide: https://www.digitalocean.com/community/tutorials/how-to-use-bash-history-commands-and-expansions-on-a-linux-vps
+HISTCONTROL=ignoreboth                   # don't put duplicate lines or lines starting with space in the history.
 export HISTSIZE=100000                   # big big history
 export HISTFILESIZE=100000               # big big history
 shopt -s histappend
